           

           <label for="id" class="label">
                <span><?php echo __('Enter Id') ?></span>
            </label>
            <div class="control">
                <input type="text" id="id" name="product[cust_id]" class="admin__control-text required-entry" maxlength="255" title="id">
            </div>


            <label for="name" class="label">
                <span><?php echo __('Enter Name') ?></span>
            </label>
            <div class="control">
                <input type="text" id="name" name="product[cust_name]" class="admin__control-text required-entry" maxlength="255" title="name">
            </div>

            
			<label for="prod" class="label">
                <span><?php echo __('Enter Product') ?></span>
            </label>
            <div class="control">
                <input type="text" id="prod" name="prod[cust_prod]" class="admin__control-text  required-entry" maxlength="255" title="prod">
            </div>
